Подключение Vuex. Работа с глобальным состоянием приложения
htmlacademy-vue/1923175-pizza-1 pull request #7
Opened 2022-03-02 06:28 UTC by rSergey92

2022-03-14 21:21 UTC, enotke requested changes

2022-03-14 21:21 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
>        type="button"
В этом компоненте осталось лишнее состояние (amount).

2022-03-14 21:21 UTC, enotke commented on src/frontend/src/common/components/ItemCounter.vue
>        type="button"
И в этот компонент можно передавать только amount и ingredient.id

2022-03-14 21:21 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> -            :checked="pizza.id === doughId"
Наверное dough.id

2022-03-14 21:21 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +            @change="getDoughID(pizza.id)"
Правильнее будет setDoughId

2022-03-14 21:21 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderIngredientsSelector.vue
> +              @change="getSaucesId"
setSaucesId

2022-03-14 21:21 UTC, enotke commented on src/frontend/src/store/modules/builder/mutations.js
> +    --item.amount;
Тут лучше передавать item.id, находить этот элемент в state и менять amount

2022-03-15 21:21 UTC, enotke commented
В первый раз не заметил. В корзине можно купить отрицательное количество пиццы.

2022-03-15 21:22 UTC, enotke commented
Футер в корзине куда-то съехал

2022-03-15 21:26 UTC, enotke commented
Функционал добавления дополнительных позиций в заказ должен работать

2022-03-18 07:45 UTC, enotke commented
@rSergey92

2022-03-18 07:46 UTC, rSergey92 commented
Я видел замечания

2022-03-18 07:49 UTC, rSergey92 commented
> @rSergey92

Я видел замечания, исправил, не доделал только 
> Функционал добавления дополнительных позиций в заказ должен работать

2022-03-22 20:57 UTC, merged