Добавление анимаций в проект
htmlacademy-vue/1923175-pizza-1 pull request #9
Opened 2022-04-15 09:59 UTC by rSergey92

2022-04-15 22:20 UTC, enotke commented
![image](https://user-images.githubusercontent.com/88033634/163648964-e4c6f95c-96bf-4c1b-ad77-dbfdc7fb6c44.png)
Ошибки в корзине

2022-04-15 22:20 UTC, enotke commented
Сломалась кнопка "Оформить заказ"

2022-04-15 22:22 UTC, enotke requested changes

2022-04-15 22:22 UTC, enotke commented on src/frontend/public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
У тебя же простые анимации зачем подключать библиотеку?

2022-04-18 05:56 UTC, enotke commented
После оформления заказа нужно очищать корзину

2022-04-18 05:58 UTC, enotke commented
Пропала анимация перехода между страницами

2022-04-18 06:05 UTC, rSergey92 commented on src/frontend/public/index.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
После отключения библиотеки пропала анимация

2022-04-18 19:24 UTC, rSergey92 commented
@enotke Внесены правки по ревью
Не стал отключать библиотеку и пилить собственную реализацию анимация для переключения по страницам

2022-04-18 21:20 UTC, merged

2022-04-18 21:21 UTC, enotke commented
@rSergey92 Так там же почти ничего не нужно писать для анимации перехода